//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blockchain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ID { get; set; }
        public int EventID { get; set; }
        public System.DateTime Date { get; set; }
        public string Title { get; set; }
        public int Day { get; set; }
        public System.TimeSpan Time { get; set; }
        public Nullable<int> UserModeratorID { get; set; }
        public Nullable<int> UserJury1ID { get; set; }
        public Nullable<int> UserJury2ID { get; set; }
        public Nullable<int> UserJury3ID { get; set; }
        public Nullable<int> UserJury4ID { get; set; }
        public Nullable<int> UserJury5ID { get; set; }
        public Nullable<int> UserParticipantID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual User User4 { get; set; }
        public virtual User User5 { get; set; }
        public virtual User User6 { get; set; }
    }
}
